const KEY='cod-rhino-v2';
const storehousePower=[0,5,7,14,38,89,198,399,775,1486,2845,4549,6700,9433,12939,17485,23444,31351,42029,56647,76829,104963,145963,205216,295582,478364];
const buildingSchema=[
 {name:'Hall of Order',category:'Command',levels:[null]},
 {name:'Wall',category:'Command',levels:[null]},
 {name:'Rally Beacon',category:'Command',levels:[24],note:'Verified from Rhino account'},
 {name:'Watch Tower',category:'Command',levels:[null]},
 {name:'Celestial Temple',category:'Command',levels:[null]},
 {name:'College of Order',category:'Research & Alliance',levels:[null]},
 {name:'Alliance Center',category:'Research & Alliance',levels:[null]},
 {name:'Alliance Market',category:'Research & Alliance',levels:[null]},
 {name:'Storehouse',category:'Support',levels:[null],power:storehousePower},
 {name:'Scout Camp',category:'Support',levels:[null]},
 {name:'Abbey',category:'Support',levels:[null]},
 {name:'Swordsmen Camp',category:'Troop Training',levels:[null]},
 {name:'Ballista Factory',category:'Troop Training',levels:[null]},
 {name:'Knight Camp',category:'Troop Training',levels:[null]},
 {name:'Mint',category:'Resource Production',levels:[25,24,23,23]},
 {name:'Lumber Mill',category:'Resource Production',levels:[25,24,24,23]},
 {name:'Foundry',category:'Resource Production',levels:[25,23,23,23]},
 {name:'Mana Production',category:'Resource Production',levels:[25,23,23,23]}
];
const seed={account:{name:'Rhino',faction:'League of Order',troops:1500000,tier:'T4'},buildings:buildingSchema,economy:[{name:'Architecture I',level:10,max:10},{name:'Scholarship I',level:10,max:10},{name:'Engineering I',level:10,max:10},{name:'Resource Production',level:9,max:10}],military:[{name:'Defensive Formations I',level:9,max:10,perLevel:1,effect:'DEF +9%'},{name:'Legion Capacity I',level:10,max:10},{name:'Infantry Combat',level:8,max:10},{name:'Cavalry Combat',level:8,max:10},{name:'Marksman Combat',level:8,max:10},{name:'Magic Combat',level:8,max:10}],heroes:{owned:'Legendary roster tracked separately',recent:'Thanatil + Shang Ying',focus:'Best possible configuration'},crystals:{g6:38,legendary:135,epic:77,rare:15}};
function migrate(){let old=JSON.parse(localStorage.getItem('cod-rhino-v1')||'null');let current=JSON.parse(localStorage.getItem(KEY)||'null');if(current)return current;let fresh=structuredClone(seed);if(old){fresh.account={...fresh.account,...old.account};for(const b of old.buildings||[]){let hit=fresh.buildings.find(x=>x.name===b.name);if(hit)hit.levels=b.levels;}fresh.economy=old.economy||fresh.economy;fresh.military=old.military||fresh.military;fresh.heroes=old.heroes||fresh.heroes;fresh.crystals=old.crystals||fresh.crystals;}return fresh}
let data=migrate();
const pages=['Overview','Buildings','Economy Tech','Military Tech','Heroes & Assets','Data'];let page='Overview';
const $=s=>document.querySelector(s);const pct=(arr)=>Math.round(arr.reduce((a,x)=>a+x.level,0)/arr.reduce((a,x)=>a+x.max,0)*100);const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));$('#saveState').textContent='● Saved locally'};
const knownBuildingLevels=()=>data.buildings.flatMap(b=>b.levels).filter(v=>Number.isFinite(v));
const buildingPct=()=>{let v=knownBuildingLevels();return v.length?Math.round(v.reduce((a,b)=>a+b,0)/(v.length*25)*100):0};
function nav(){ $('#nav').innerHTML=pages.map(x=>`<button class="${x===page?'active':''}" data-page="${x}">${x}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function ring(v,label){return `<div class="card span4"><div class="section-label">${label}</div><div class="ring" style="--p:${v}"><strong>${v}%</strong></div></div>`}
function kpi(label,value,sub,p=0){return `<div class="card span3 kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div>${p?`<div class="bar"><i style="width:${p}%"></i></div>`:''}</div>`}
function overview(){let bp=buildingPct(),ep=pct(data.economy),mp=pct(data.military),known=knownBuildingLevels().length,total=data.buildings.reduce((n,b)=>n+b.levels.length,0);return `<div class="grid">${kpi('Account',data.account.name,data.account.faction)}${kpi('Troop Force',Intl.NumberFormat().format(data.account.troops),data.account.tier+' modeled force')}${kpi('Building status',bp+'%',known+' of '+total+' building instances populated',bp)}${kpi('Tech composite',Math.round((ep+mp)/2)+'%','Known technology dataset',Math.round((ep+mp)/2))}${ring(bp,'Known building progression')}${ring(ep,'Economy technology')}${ring(mp,'Military technology')}<div class="card span12"><div class="section-label">Command assessment</div><h2>Rhino progression model</h2><p class="mini">The building model now uses the full League of Order schema rather than only the five building types previously entered. Blank levels mean account data has not yet been verified; blanks are excluded from completion scoring so unknown values never masquerade as level zero.</p><div class="notice">Verified Rhino values retained: Rally Beacon 24; Mint 25/24/23/23; Lumber Mill 25/24/24/23; Foundry 25/23/23/23; Mana Production 25/23/23/23.</div></div></div>`}
function buildingPower(b,v){if(!Number.isFinite(v)||!b.power)return null;return b.power[v]??null}
function buildingRow(b,i){let vals=b.levels.filter(Number.isFinite),maxed=vals.length===b.levels.length&&vals.every(v=>v===25),known=vals.length===b.levels.length;let cpParts=b.levels.map(v=>buildingPower(b,v)).filter(v=>v!==null);let cp=b.power&&cpParts.length===b.levels.length?cpParts.reduce((a,x)=>a+x,0):null;let cpMax=b.power?b.levels.length*b.power[25]:null;return `<div class="list-row"><div><b>${b.name}</b><br><small>${b.category}${b.note?' • '+b.note:''}</small></div><div class="levels">${b.levels.map((v,j)=>`<input type="number" min="1" max="25" placeholder="—" value="${Number.isFinite(v)?v:''}" data-building="${i}" data-slot="${j}">`).join('')}</div><div style="min-width:180px;text-align:right"><span class="status">${maxed?'MAX':known?'IN PROGRESS':'NEEDS DATA'}</span><br><small>${cp!==null?Intl.NumberFormat().format(cp)+' / '+Intl.NumberFormat().format(cpMax)+' static CP':'Static CP table pending verification'}</small></div></div>`}
function buildings(){let bp=buildingPct(),known=knownBuildingLevels().length,total=data.buildings.reduce((n,b)=>n+b.levels.length,0),groups=[...new Set(data.buildings.map(b=>b.category))];return `<div class="grid">${kpi('Known completion',bp+'%',known+' of '+total+' instances populated',bp)}${kpi('Schema coverage',data.buildings.length+' types',total+' total building instances')}${kpi('Max level','25','Per permanent city building')}${kpi('Data integrity',total-known+' unknown','Excluded from scoring')}<div class="card span12"><div class="section-label">League of Order building model • editable levels 1–25</div><p class="mini">Every permanent building type in the current League of Order model is represented below. Enter only values verified in-game. Known static CP is calculated where a verified level-power table is loaded; other CP rows remain explicitly unverified rather than estimated.</p>${groups.map(g=>`<h3 style="margin:24px 0 4px;color:#f2c45c">${g}</h3>${data.buildings.map((b,i)=>b.category===g?buildingRow(b,i):'').join('')}`).join('')}</div></div>`}
function tech(type){let arr=data[type],title=type==='economy'?'Economy Technology':'Military Technology';return `<div class="grid">${ring(pct(arr),title+' completion')}<div class="card span8"><div class="section-label">Editable research status</div>${arr.map((t,i)=>`<div class="tech-row"><div><b>${t.name}</b><br><small>${t.effect||'Progress tracked'}</small></div><input type="number" min="0" max="${t.max}" value="${t.level}" data-tech="${type}" data-index="${i}"><div class="bar"><i style="width:${t.level/t.max*100}%"></i></div><span class="status">${t.level}/${t.max}</span></div>`).join('')}</div><div class="card span12 notice">Technology is still a partial model; the next schema expansion should apply the same canonical-tree approach used for Buildings.</div></div>`}
function assets(){return `<div class="grid">${kpi('Hero roster',data.heroes.owned,'Roster note')}${kpi('Recent focus',data.heroes.recent,'G6 Cavalry')}${kpi('G6 crystals',data.crystals.g6,'Generic')}${kpi('Legendary crystals',data.crystals.legendary,'Generic')}<div class="card span12"><div class="section-label">Account objective</div><h2>${data.heroes.focus}</h2></div></div>`}
function raw(){return `<div class="card"><div class="section-label">Portable account repository</div><p class="mini">Your edits persist in this browser. Export creates a JSON snapshot.</p><pre style="white-space:pre-wrap;color:#9fc7d6">${JSON.stringify(data,null,2)}</pre></div>`}
function bind(){document.querySelectorAll('[data-building]').forEach(x=>x.onchange=()=>{let raw=x.value.trim();data.buildings[+x.dataset.building].levels[+x.dataset.slot]=raw===''?null:Math.max(1,Math.min(25,+raw));save();render()});document.querySelectorAll('[data-tech]').forEach(x=>x.onchange=()=>{let t=data[x.dataset.tech][+x.dataset.index];t.level=Math.max(0,Math.min(t.max,+x.value));if(t.name==='Defensive Formations I')t.effect=`DEF +${t.level*(t.perLevel||1)}%`;save();render()})}
function render(){nav();$('#pageTitle').textContent=page;let c=$('#content');c.innerHTML=page==='Overview'?overview():page==='Buildings'?buildings():page==='Economy Tech'?tech('economy'):page==='Military Tech'?tech('military'):page==='Heroes & Assets'?assets():raw();bind()}
$('#resetBtn').onclick=()=>{if(confirm('Reset all dashboard edits to the seeded Rhino dataset?')){data=structuredClone(seed);save();render()}};$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='rhino-account-data.json';a.click()};save();render();