const KEY='cod-rhino-v1';
const seed={account:{name:'Rhino',faction:'League of Order',troops:1500000,tier:'T4'},buildings:[{name:'Rally Beacon',levels:[24],note:'Upgrade to 25 identified'},{name:'Mint',levels:[25,24,23,23]},{name:'Lumber Mill',levels:[25,24,24,23]},{name:'Foundry',levels:[25,23,23,23]},{name:'Mana Production',levels:[25,23,23,23]}],economy:[{name:'Architecture I',level:10,max:10},{name:'Scholarship I',level:10,max:10},{name:'Engineering I',level:10,max:10},{name:'Resource Production',level:9,max:10}],military:[{name:'Defensive Formations I',level:9,max:10,perLevel:1,effect:'DEF +9%'},{name:'Legion Capacity I',level:10,max:10},{name:'Infantry Combat',level:8,max:10},{name:'Cavalry Combat',level:8,max:10},{name:'Marksman Combat',level:8,max:10},{name:'Magic Combat',level:8,max:10}],heroes:{owned:'All except Shang Ying and Falgrim',recent:'Zayda obtained',focus:'Best possible configuration'},crystals:{g6:38,legendary:135,epic:77,rare:15}};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
const pages=['Overview','Buildings','Economy Tech','Military Tech','Heroes & Assets','Data'];let page='Overview';
const $=s=>document.querySelector(s);const pct=(arr)=>Math.round(arr.reduce((a,x)=>a+x.level,0)/arr.reduce((a,x)=>a+x.max,0)*100);const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));$('#saveState').textContent='● Saved locally'};
function nav(){ $('#nav').innerHTML=pages.map(x=>`<button class="${x===page?'active':''}" data-page="${x}">${x}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function ring(v,label){return `<div class="card span4"><div class="section-label">${label}</div><div class="ring" style="--p:${v}"><strong>${v}%</strong></div></div>`}
function kpi(label,value,sub,p=0){return `<div class="card span3 kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div>${p?`<div class="bar"><i style="width:${p}%"></i></div>`:''}</div>`}
function overview(){let bp=Math.round(data.buildings.flatMap(x=>x.levels).reduce((a,b)=>a+b,0)/(data.buildings.flatMap(x=>x.levels).length*25)*100),ep=pct(data.economy),mp=pct(data.military);return `<div class="grid">${kpi('Account',data.account.name,data.account.faction)}${kpi('Troop Force',Intl.NumberFormat().format(data.account.troops),data.account.tier+' modeled force')}${kpi('Building status',bp+'%','Known building dataset',bp)}${kpi('Tech composite',Math.round((ep+mp)/2)+'%','Known technology dataset',Math.round((ep+mp)/2))}${ring(bp,'Building progression')}${ring(ep,'Economy technology')}${ring(mp,'Military technology')}<div class="card span12"><div class="section-label">Command assessment</div><h2>Rhino progression model</h2><p class="mini">This dashboard is deliberately data-driven. Change a building or technology level and the completion metrics recalculate immediately. Values not yet verified from your screenshots are treated as model placeholders rather than asserted game data.</p><div class="notice">Current verified building snapshots include Rally Beacon 24; Mint 25/24/23/23; Lumber 25/24/24/23; Foundry 25/23/23/23; Mana 25/23/23/23.</div></div></div>`}
function buildings(){return `<div class="card"><div class="section-label">Editable building levels • max 25</div>${data.buildings.map((b,i)=>`<div class="list-row"><b>${b.name}</b><div class="levels">${b.levels.map((v,j)=>`<input type="number" min="0" max="25" value="${v}" data-building="${i}" data-slot="${j}">`).join('')}</div><span class="status">${b.levels.every(v=>v===25)?'MAX':'IN PROGRESS'}</span></div>`).join('')}</div>`}
function tech(type){let arr=data[type],title=type==='economy'?'Economy Technology':'Military Technology';return `<div class="grid">${ring(pct(arr),title+' completion')}<div class="card span8"><div class="section-label">Editable research status</div>${arr.map((t,i)=>`<div class="tech-row"><div><b>${t.name}</b><br><small>${t.effect||'Progress tracked'}</small></div><input type="number" min="0" max="${t.max}" value="${t.level}" data-tech="${type}" data-index="${i}"><div class="bar"><i style="width:${t.level/t.max*100}%"></i></div><span class="status">${t.level}/${t.max}</span></div>`).join('')}</div><div class="card span12 notice">Only technology rows currently represented in the model are included in the percentage. Add the remaining extracted tech-tree items to make this a full-tree completion metric.</div></div>`}
function assets(){return `<div class="grid">${kpi('Hero roster',data.heroes.owned,'Roster note')}${kpi('Recent acquisition',data.heroes.recent,'Hero progression')}${kpi('G6 crystals',data.crystals.g6,'Generic')}${kpi('Legendary crystals',data.crystals.legendary,'Generic')}<div class="card span12"><div class="section-label">Account objective</div><h2>${data.heroes.focus}</h2><p class="mini">Legion configurations remain intentionally outside the scoring model until you want them incorporated.</p></div></div>`}
function raw(){return `<div class="card"><div class="section-label">Portable account repository</div><p class="mini">Your edits persist in this browser. Export creates a JSON snapshot that can later become the canonical repository dataset.</p><pre style="white-space:pre-wrap;color:#9fc7d6">${JSON.stringify(data,null,2)}</pre></div>`}
function bind(){document.querySelectorAll('[data-building]').forEach(x=>x.onchange=()=>{data.buildings[+x.dataset.building].levels[+x.dataset.slot]=Math.max(0,Math.min(25,+x.value));save();render()});document.querySelectorAll('[data-tech]').forEach(x=>x.onchange=()=>{let t=data[x.dataset.tech][+x.dataset.index];t.level=Math.max(0,Math.min(t.max,+x.value));if(t.name==='Defensive Formations I')t.effect=`DEF +${t.level*(t.perLevel||1)}%`;save();render()})}
function render(){nav();$('#pageTitle').textContent=page;let c=$('#content');c.innerHTML=page==='Overview'?overview():page==='Buildings'?buildings():page==='Economy Tech'?tech('economy'):page==='Military Tech'?tech('military'):page==='Heroes & Assets'?assets():raw();bind()}
$('#resetBtn').onclick=()=>{if(confirm('Reset all dashboard edits to the seeded Rhino dataset?')){data=structuredClone(seed);save();render()}};$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='rhino-account-data.json';a.click()};render();