// V3 UI overlay: grouped graphical Buildings view backed by verified master data.
(()=>{
  if(typeof data==='undefined'||typeof master==='undefined')return;
  if(Number(data.schemaVersion||0)<3){data=structuredClone(window.COD_PROFILE_RHINO);save();}
  const f=n=>new Intl.NumberFormat().format(Math.round(Number(n||0))),p=n=>Math.round(n*10)/10;
  buildings=function(){
    const h=COD_ENGINE.health(master,data),cur=Number(data.currentBuildingPower||0),max=Number(master.staticPower?.allLevel25BuildingPower||0),rem=Math.max(0,max-cur),cpPct=max?cur/max*100:0;
    const order=master.buildingDisplayGroups||[...new Set(master.buildings.map(b=>b.group))];
    const card=b=>{const vals=data.buildings[b.id]||[],lc=vals.reduce((a,v)=>a+Number(v||0),0),lm=b.slots*b.maxLevel,lp=lm?lc/lm*100:0,bc=data.buildingPowerById?.[b.id],bm=b.maxPower,known=Number.isFinite(Number(bc))&&Number.isFinite(Number(bm));const selectors=Array.from({length:b.slots},(_,j)=>`<label style="display:inline-flex;align-items:center;gap:5px;margin:4px 6px 4px 0"><small>${b.slots>1?'#'+(j+1):'Level'}</small><select data-building="${b.id}" data-slot="${j}">${Array.from({length:b.maxLevel+1},(_,v)=>`<option ${Number(vals[j]||0)===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('');return `<div class="card span4"><div class="section-label">${b.group}</div><h2 style="margin-bottom:4px">${b.label}</h2><div class="tree-summary"><b>${p(lp)}%</b><span>${f(lc)} / ${f(lm)} levels</span></div><div class="bar"><i style="width:${lp}%"></i></div><div style="margin:10px 0">${selectors}</div><div class="metric"><span>Static CP</span><b>${known?f(bc)+' / '+f(bm):'Pending curve'}</b></div><div class="metric"><span>Remaining CP</span><b>${known?f(Math.max(0,bm-bc)):'—'}</b></div><span class="status">${lp===100?'MAX':p(lp)+'%'}</span></div>`};
    const grouped=order.map(g=>{const bs=master.buildings.filter(b=>b.group===g);if(!bs.length)return'';const gc=bs.reduce((a,b)=>a+(data.buildings[b.id]||[]).reduce((x,v)=>x+Number(v||0),0),0),gm=bs.reduce((a,b)=>a+b.slots*b.maxLevel,0),gp=gm?gc/gm*100:0;return `<div class="card span12"><div class="section-label">${g.toUpperCase()}</div><div class="tree-summary"><b>${p(gp)}%</b><span>${f(gc)} / ${f(gm)} building levels</span></div></div>${bs.map(card).join('')}`}).join('');
    const gaps=master.buildings.map(b=>({label:b.label,remaining:Math.max(0,Number(b.maxPower||0)-Number(data.buildingPowerById?.[b.id]||0))})).filter(x=>x.remaining>0).sort((a,b)=>b.remaining-a.remaining).slice(0,5);
    return `<div class="grid">${kpi('Building Completion',p(h.buildings.pct)+'%',`${f(h.buildings.current)} / ${f(h.buildings.max)} total building levels`,h.buildings.pct)}${kpi('Building Static CP',f(cur),`${f(max)} maximum`,cpPct)}${kpi('Remaining Building CP',f(rem),'Static CP still available')}${kpi('Building Instances',f(master.buildings.reduce((a,b)=>a+b.slots,0)),'Controlled game-defined slots')}<div class="card span12"><div class="section-label">BUILDING DEVELOPMENT • GROUPED ACCOUNT VIEW</div><h2>Rhino city status from current state → all Level 25</h2><div class="mini">Game constants stay fixed; selectors update only this player's account state. CP values shown are verified static values where available.</div></div>${grouped}<div class="card span12"><div class="section-label">NEXT DEVELOPMENT • VERIFIED CP OPPORTUNITY</div><div class="mini">Largest remaining static-CP pools. Final recommendations will add prerequisites, queue, time and resource-cost weighting.</div>${gaps.map((x,i)=>`<div class="metric"><span>${i+1}. ${x.label}</span><b>${f(x.remaining)} CP</b></div>`).join('')}</div></div>`;
  };if(typeof render==='function')render();
})();