// V3 UI overlay: executive grouped presentation over the verified master-data foundation.
(()=>{
 if(typeof data==='undefined'||typeof master==='undefined')return;
 // Profile migration belongs to the app persistence layer. Never call the retired save() function here.
 // Older locally stored profiles remain usable and are rendered against the V3 master schema.
 if(Number(data.schemaVersion||0)<3)data.schemaVersion=3;
 const f=n=>new Intl.NumberFormat().format(Math.round(Number(n||0))),p=n=>Math.round(n*10)/10,groupOrder=['Command','Research','Military','Support','Economy'],groupMeta=master.buildingGroups||{};
 const state=v=>v===100?'MAX':v>=95?'NEAR MAX':v>=80?'ADVANCED':'DEVELOPING';
 const techColorMeta=[
  {key:'gray',label:'Normal',note:'Earliest technology family'},
  {key:'green',label:'Advanced',note:'Second technology family'},
  {key:'blue',label:'Elite',note:'Third technology family'},
  {key:'purple',label:'Epic',note:'Fourth technology family'},
  {key:'gold',label:'Legendary',note:'Highest technology family'},
  {key:'unmapped',label:'Source mapping pending',note:'Awaiting in-game screenshot verification'}
 ];
 const techTierKey=t=>{const x=String(t.tier||t.rarity||t.colorTier||'').toLowerCase();if(x==='grey')return'gray';return ['gray','green','blue','purple','gold'].includes(x)?x:'unmapped'};
 function techRowExec(type,t){const lv=Number(data.technology[type]?.[t.id]||0),pc=t.maxLevel?lv/t.maxLevel*100:0,tier=techTierKey(t);return `<div class="tech-row tier-${tier}"><div><b>${t.label}</b><br><small>${t.displayGroup} • ${tier==='unmapped'?'color pending':techColorMeta.find(x=>x.key===tier)?.label||tier}</small></div><select data-tech="${type}" data-id="${t.id}">${Array.from({length:t.maxLevel+1},(_,v)=>`<option ${lv===v?'selected':''}>${v}</option>`).join('')}</select><div class="bar"><i style="width:${pc}%"></i></div><span class="status">${lv}/${t.maxLevel}</span></div>`}
 tech=function(type){const h=COD_ENGINE.techProgress(master,data,type),title=type==='economy'?'Economy Technology':'Military Technology',nodes=master.technology[type];const groups=techColorMeta.map(meta=>{const items=nodes.filter(t=>techTierKey(t)===meta.key);return `<div class="tech-tier-card tier-card-${meta.key}"><div class="tech-tier-head"><div><b>${meta.label}</b><small>${meta.note}</small></div><strong>${items.length} technolog${items.length===1?'y':'ies'}</strong></div>${items.length?items.map(t=>techRowExec(type,t)).join(''):`<div class="tier-empty">No technologies are authoritatively mapped to this color yet.</div>`}</div>`}).join('');return `<div class="grid">${ring(h.pct,title,`${h.current}/${h.max} levels`)}<div class="card span8"><div class="section-label">IN-GAME COLOR / RARITY FAMILIES</div><h2>${title} by technology color</h2><div class="notice">Technology families follow the in-game icon-background sequence: gray → green → blue → purple → yellow/gold. The panel background carries the family color so the color name does not need to be repeated on every row. Screenshot-verified Military nodes are mapped now; any technology not yet visually verified remains in Source mapping pending.</div>${groups}</div></div>`};
 function singleRow(b){const vals=data.buildings[b.id]||[],v=Number(vals[0]||0),pct=b.maxLevel?v/b.maxLevel*100:0,cur=data.buildingPowerById?.[b.id],max=b.maxPower,known=Number.isFinite(Number(cur))&&Number.isFinite(Number(max));return `<div class="building-row-exec"><div class="building-name"><b>${b.label}</b><small>${b.group}</small></div><div class="building-levels"><select data-building="${b.id}" data-slot="0">${Array.from({length:b.maxLevel+1},(_,x)=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="building-progress"><div class="building-progress-line"><span>${v} / ${b.maxLevel} levels</span><b>${p(pct)}%</b></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="building-cp"><b>${known?f(cur)+' CP':'—'}</b><small>${known?f(max)+' max • '+f(Math.max(0,max-cur))+' remaining':'CP curve pending'}</small></div><div class="building-state ${pct===100?'is-max':''}">${state(pct)}</div></div>`}
 function familyRows(b){const vals=data.buildings[b.id]||[],total=vals.reduce((a,v)=>a+Number(v||0),0),maxLevels=b.slots*b.maxLevel,pct=maxLevels?total/maxLevels*100:0,cur=data.buildingPowerById?.[b.id],max=b.maxPower,known=Number.isFinite(Number(cur))&&Number.isFinite(Number(max)),labels=b.childLabels||Array.from({length:b.slots},(_,i)=>`${b.label} ${i+1}`);let html=`<div class="building-row-exec building-parent"><div class="building-name"><b>${b.label}</b><small>Aggregate • ${b.slots} ${b.childKind==='troop-type'?'troop types':'structures'}</small></div><div class="building-levels"><b>${f(total)} / ${f(maxLevels)}</b></div><div class="building-progress"><div class="building-progress-line"><span>Aggregate completion</span><b>${p(pct)}%</b></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="building-cp"><b>${known?f(cur)+' CP':'—'}</b><small>${known?f(max)+' max • '+f(Math.max(0,max-cur))+' remaining':'CP curve pending'}</small></div><div class="building-state ${pct===100?'is-max':''}">${state(pct)}</div></div>`;html+=vals.map((v,i)=>{const cpct=b.maxLevel?Number(v||0)/b.maxLevel*100:0;return `<div class="building-row-exec building-child"><div class="building-name"><b>${labels[i]||`${b.label} ${i+1}`}</b><small>${b.childKind==='troop-type'?'Troop type':'Child structure'}</small></div><div class="building-levels"><select data-building="${b.id}" data-slot="${i}">${Array.from({length:b.maxLevel+1},(_,x)=>`<option ${Number(v||0)===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="building-progress"><div class="building-progress-line"><span>${Number(v||0)} / ${b.maxLevel} levels</span><b>${p(cpct)}%</b></div><div class="bar"><i style="width:${cpct}%"></i></div></div><div class="building-cp"><b>Included in parent</b><small>Aggregate static CP</small></div><div class="building-state ${cpct===100?'is-max':''}">${state(cpct)}</div></div>`}).join('');return html}
 function buildingRow(b){return b.slots>1?familyRows(b):singleRow(b)}
 buildings=function(){const h=COD_ENGINE.health(master,data),cur=Number(data.currentBuildingPower||0),max=Number(master.staticPower?.allLevel25BuildingPower||0),rem=Math.max(0,max-cur),cpPct=max?cur/max*100:0;const sections=groupOrder.map(key=>{const items=master.buildings.filter(b=>b.group===key);if(!items.length)return'';const meta=groupMeta[key]||{label:key,description:''},curLv=items.reduce((s,b)=>s+(data.buildings[b.id]||[]).reduce((a,v)=>a+Number(v||0),0),0),maxLv=items.reduce((s,b)=>s+b.slots*b.maxLevel,0),gp=maxLv?curLv/maxLv*100:0;return `<div class="card span12 building-group-card"><div class="building-group-head"><div><div class="section-label">${meta.label.toUpperCase()}</div><h2>${meta.label}</h2><div class="mini">${meta.description}</div></div><div class="group-score"><strong>${p(gp)}%</strong><span>${f(curLv)} / ${f(maxLv)} levels</span><div class="bar"><i style="width:${gp}%"></i></div></div></div><div class="building-table-head"><span>STRUCTURE</span><span>LEVEL</span><span>COMPLETION</span><span>COMBAT POWER</span><span>STATUS</span></div>${items.map(buildingRow).join('')}</div>`}).join('');const gaps=master.buildings.map(b=>({label:b.label,remaining:Math.max(0,Number(b.maxPower||0)-Number(data.buildingPowerById?.[b.id]||0))})).filter(x=>x.remaining>0).sort((a,b)=>b.remaining-a.remaining).slice(0,5);return `<div class="grid buildings-exec">${kpi('Building Completion',`${p(h.buildings.pct)}%`,`${f(h.buildings.current)} / ${f(h.buildings.max)} total levels`,h.buildings.pct)}${kpi('Verified Building CP',f(cur),`${f(max)} all-Lv25 maximum`,cpPct)}${kpi('Remaining Verified CP',f(rem),`${p(100-cpPct)}% of static building CP remains`)}${kpi('Building Instances',`${master.buildings.reduce((a,b)=>a+b.slots,0)}`,'Controlled city structures')}${sections}<div class="card span12"><div class="section-label">EXECUTIVE DEVELOPMENT VIEW</div><h2>Largest remaining static-CP opportunities</h2><div class="opportunity-strip">${gaps.map((x,i)=>`<div><span>${i+1}</span><b>${x.label}</b><strong>${f(x.remaining)} CP</strong></div>`).join('')}</div></div></div>`};if(typeof render==='function')render();
})();